<?php

namespace App\Enums;

enum OtpType: string
{
    case RESET_PASSWORD_VERIFICATION = 'RESET_PASSWORD_VERIFICATION';

    case SIGNUP_EMAIL_VERIFICATION = 'SIGNUP_EMAIL_VERIFICATION';

    case RESET_MULTI_FACTOR_AUTHENTICATION = 'RESET_MULTI_FACTOR_AUTHENTICATION';

    case CHANGE_EMAIL_VERIFICATION = 'CHANGE_EMAIL_VERIFICATION';

    case SUPPLIER_ADD_BANK_ACCOUNT = 'SUPPLIER_ADD_BANK_ACCOUNT';

}
